FROM container-registry.phenomenal-h2020.eu/phnmnl/midcor:latest
MAINTAINER PhenoMeNal-H2020 Project ( phenomenal-h2020-users@googlegroups.com )

# run the test file
RUN runTest1.sh
# we are currently not testing for the correctness of the run, but at least we know that is running without issues.
